import Image from "next/image";
import { ActionForm, Field } from "@/components/action-form";
import { saveProduct, archiveProduct, saveVariant, uploadImage, updateImage, removeImage, moveImage } from "@/app/admin/actions";
import type { adminProduct, adminOptions } from "@/lib/admin/repository";
import { mapProduct } from "@/lib/catalog/mapper";
type Product = NonNullable<Awaited<ReturnType<typeof adminProduct>>>;
type Options = Awaited<ReturnType<typeof adminOptions>>;
function Hidden({ productId, image }: {
    productId: string;
    image: {
        id: string;
        updated_at: string;
    };
}) { return <><input type="hidden" name="product_id" value={productId}/><input type="hidden" name="id" value={image.id}/><input type="hidden" name="updated_at" value={image.updated_at}/></>; }
function VariantFields({ variant }: {
    variant?: Product["product_variants"][number];
}) { return <><div className="form-grid"><Field label="SKU" name="sku" defaultValue={variant?.sku} required maxLength={100}/><Field label="SIZE" name="size" defaultValue={variant?.size} required maxLength={40}/><Field label="COLOR" name="color" defaultValue={variant?.color} required maxLength={80}/><Field label="STOCK" name="stock_quantity" type="number" defaultValue={variant?.stock_quantity ?? 0} required min={0} max={1000000} step="1"/></div><label className="check-field"><input type="checkbox" name="is_active" defaultChecked={variant?.is_active ?? true}/>Active variant</label></>; }
export function ProductEditor({ product, options }: {
    product?: Product;
    options: Options;
}) {
    return <><ActionForm action={saveProduct} label={product ? "SAVE PRODUCT" : "CREATE PRODUCT"}><input type="hidden" name="id" value={product?.id ?? ""}/><input type="hidden" name="updated_at" value={product?.updated_at ?? ""}/>
 <section className="panel"><h2>GENERAL</h2><div className="form-grid"><Field label="NAME" name="name" defaultValue={product?.name} required maxLength={200}/><Field label="SLUG" name="slug" defaultValue={product?.slug} required maxLength={160}/></div><label className="k-field"><span>DESCRIPTION</span><textarea name="description" defaultValue={product?.description} maxLength={10000} rows={5}/></label></section>
 <section className="panel"><h2>PRICING</h2><div className="form-grid"><Field label="PRICE · GEL" name="price" defaultValue={product ? (product.price / 100).toFixed(2) : ""} type="number" min={0} step="0.01" required/><Field label="COMPARE-AT PRICE · GEL" name="compare_at_price" defaultValue={product?.compare_at_price != null ? (product.compare_at_price / 100).toFixed(2) : ""} type="number" min={0} step="0.01"/></div></section>
 <section className="panel"><h2>ORGANIZATION</h2><label className="k-field"><span>CATEGORY</span><select name="category_id" required defaultValue={product?.category_id ?? ""}><option value="" disabled>Choose a category</option>{options.categories.map(c => <option value={c.id} key={c.id}>{c.name}{c.is_active ? "" : " (inactive)"}</option>)}</select></label>{!options.categories.length && <p className="muted">Create a category in Supabase before adding products.</p>}<fieldset className="check-list"><legend>COLLECTIONS</legend>{options.collections.map(c => <label className="check-field" key={c.id}><input type="checkbox" name="collections" value={c.id} defaultChecked={product?.product_collections.some(pc => pc.collection_id === c.id)}/>{c.name}{c.is_active ? "" : " (inactive)"}</label>)}{!options.collections.length && <p className="muted">No collections yet.</p>}</fieldset></section>
 <section className="panel"><h2>VISIBILITY</h2><label className="k-field"><span>STATUS</span><select name="status" defaultValue={product?.status ?? "draft"}><option value="draft">Draft</option><option value="active">Active</option>{product?.status === "archived" && <option value="archived">Archived</option>}</select></label><label className="check-field"><input type="checkbox" name="featured" defaultChecked={product?.featured}/>Featured on homepage</label><label className="check-field"><input type="checkbox" name="is_drop" defaultChecked={product?.is_drop}/>Part of the current drop</label></section>
 <section className="panel"><h2>SEO</h2><Field label="SEO TITLE" name="seo_title" defaultValue={product?.seo_title ?? ""} maxLength={200}/><label className="k-field"><span>SEO DESCRIPTION</span><textarea name="seo_description" defaultValue={product?.seo_description ?? ""} maxLength={500} rows={3}/></label></section></ActionForm>
 {product ? <><section className="panel"><h2>MEDIA</h2><p className="muted">JPEG, PNG or WebP · up to 3 MB and 25 megapixels. Uploaded assets are public.</p><div className="admin-image-grid">{product.product_images.map((image, index) => <article className="image-editor" key={image.id}><Image src={mapProduct({ ...product, category: null, variants: product.product_variants, images: [image] }, process.env.SUPABASE_URL).image} alt={image.alt_text ?? product.name} width={400} height={400}/><ActionForm action={updateImage} label="SAVE ALT TEXT"><Hidden productId={product.id} image={image}/><Field label="ALT TEXT" name="alt_text" defaultValue={image.alt_text ?? ""} maxLength={500}/></ActionForm><div className="image-controls">{index > 0 && <ActionForm action={moveImage} label="MOVE UP"><Hidden productId={product.id} image={image}/><input type="hidden" name="direction" value="up"/></ActionForm>}{index < product.product_images.length - 1 && <ActionForm action={moveImage} label="MOVE DOWN"><Hidden productId={product.id} image={image}/><input type="hidden" name="direction" value="down"/></ActionForm>}<ActionForm action={removeImage} label="REMOVE" confirm="Remove this product image?"><Hidden productId={product.id} image={image}/></ActionForm></div></article>)}</div><ActionForm action={uploadImage} label="UPLOAD IMAGE"><input type="hidden" name="product_id" value={product.id}/><label className="k-field"><span>IMAGE FILE</span><input type="file" name="image" accept="image/jpeg,image/png,image/webp" required/></label><Field label="ALT TEXT" name="alt_text" maxLength={500}/></ActionForm></section>
 <section className="panel"><h2>VARIANTS & INVENTORY</h2>{!product.product_variants.length ? <p>No variants yet.</p> : <div className="table-scroll"><table className="k-table"><caption className="sr-only">Inventory</caption><thead><tr><th>VARIANT</th><th>SKU</th><th>STOCK</th><th>STATUS</th></tr></thead><tbody>{product.product_variants.map(v => <tr key={v.id}><td>{v.color} / {v.size}</td><td>{v.sku}</td><td>{v.stock_quantity}</td><td>{v.is_active ? "Active" : "Inactive"}</td></tr>)}</tbody></table></div>}
 {product.product_variants.map(v => <details className="variant-editor" key={v.id}><summary>Edit {v.color} / {v.size} · {v.sku}</summary><ActionForm action={saveVariant} label="SAVE VARIANT"><Hidden productId={product.id} image={v}/><VariantFields variant={v}/></ActionForm></details>)}
 <details className="variant-editor"><summary>ADD A VARIANT</summary><ActionForm action={saveVariant} label="ADD VARIANT"><input type="hidden" name="product_id" value={product.id}/><VariantFields /></ActionForm></details></section>
 {product.status !== "archived" && <section className="panel"><h2>ARCHIVE PRODUCT</h2><p className="muted">Hide this product while keeping historical orders intact.</p><ActionForm action={archiveProduct} label="ARCHIVE PRODUCT" confirm="Archive this product and hide it from the store?"><input type="hidden" name="id" value={product.id}/><input type="hidden" name="updated_at" value={product.updated_at}/><label className="check-field"><input type="checkbox" name="confirm_archive" required/>I want to archive this product</label></ActionForm></section>}</> : <p className="muted">Save the product first, then add images and variants.</p>}</>;
}
